services:
  # OWASP Juice Shop - http://localhost:3000
  juice-shop:
    image: bkimminich/juice-shop:latest
    ports:
      - "3000:3000"

  # OWASP WebGoat - http://localhost:8080/WebGoat
  webgoat:
    image: webgoat/webgoat:latest
    ports:
      - "8080:8080"
      - "9090:9090"
    environment:
      - TZ=America/New_York

  # DVWA - http://localhost:8081
  dvwa:
    image: vulnerables/web-dvwa:latest
    ports:
      - "8081:80"

  # bWAPP - http://localhost:8082
  bwapp:
    image: raesene/bwapp:latest
    ports:
      - "8082:80"